parameters:
    seegno_bootstrap.alerts.twig_extension.class: Seegno\BootstrapBundle\Twig\Extension\SeegnoBootstrapAlertsExtension

services:
    seegno_bootstrap.alerts.twig_extension:
        class: %seegno_bootstrap.alerts.twig_extension.class%
        arguments: ['@session', %seegno_bootstrap.alerts%]
        tags:
            - { name: twig.extension }
